name: 'Test Report'

on:
  workflow_run:
    workflows: ['Test']                     # runs after test workflow
    types:
      - completed

permissions:
  contents: read
  actions: read
  checks: write

jobs:
  report:
    runs-on: ubuntu-latest
    steps:
      - name: Build test report
        id: generateReport
        uses: dorny/test-reporter@v1
        with:
          artifact: test-results            # artifact name
          name: JEST Tests                  # Name of the check run which will be created
          path: '*.xml'                     # Path to test results (inside artifact .zip)
          reporter: jest-junit              # Format of test results
      - name: GitHub Action Summary
        if: always()
        run: |
          type summary.md | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append
